---
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "ESP32-S3 Reloj NTP + BLE"
description: "Sincronizaci√≥n WiFi y control Bluetooth con MicroPython"
show_downloads: true
---
