---
layout: default
title: "ESP32-S3 Reloj NTP + BLE"
description: "Reloj de alta precisión sincronizado por WiFi con control remoto Bluetooth y gestión avanzada de RAM en MicroPython."
theme: jekyll-theme-cayman
show_downloads: true
---
